version: '1'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
     - 5432:5432
    environment:
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: postgres
     POSTGRES_DB: testdb
    volumes:
    - ./db/init_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD","pg_isready","-U","postgres"]
      interval: 5s
      retries: 5
  app:
    build: ./app/